# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {}

modules = []

doc_url = "https://x.riddle.press/FlowNet/"

git_url = "https://github.com/professorwug/FlowNet/tree/master/"

def custom_doc_links(name): return None
