# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"SmallRandom": "01a01a Small Random Directed Graphs.ipynb",
         "plot_directed_2d": "01c Plotting Utils.ipynb",
         "plot_origin_3d": "01c Plotting Utils.ipynb",
         "plot_directed_3d": "01c Plotting Utils.ipynb",
         "plot_3d": "01c Plotting Utils.ipynb",
         "visualize_graph": "01c Plotting Utils.ipynb",
         "visualize_heatmap": "01c Plotting Utils.ipynb"}

modules = ["datasets.py"]

doc_url = "https://x.riddle.press/FlowNet/"

git_url = "https://github.com/professorwug/FlowNet/tree/master/"

def custom_doc_links(name): return None
