# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"EmailEuNetwork": "01a01a Communities Datasets.ipynb",
         "SourceSink": "01a01a Communities Datasets.ipynb",
         "SmallRandom": "01a01b Small Random Directed Graphs.ipynb",
         "DirectedStochasticBlockModel": "01a01c Directed Stochastic Block Model.ipynb",
         "source_graph": "01a01c Directed Stochastic Block Model.ipynb",
         "sink_graph": "01a01c Directed Stochastic Block Model.ipynb",
         "ChainGraph": "01a01c Directed Stochastic Block Model.ipynb",
         "ChainGraph2": "01a01c Directed Stochastic Block Model.ipynb",
         "ChainGraph3": "01a01c Directed Stochastic Block Model.ipynb",
         "CycleGraph": "01a01c Directed Stochastic Block Model.ipynb",
         "HalfCycleGraph": "01a01c Directed Stochastic Block Model.ipynb",
         "xy_tilt": "01a02a Polar 1-Manifold Toy Datasets.ipynb",
         "add_noise": "01a02a Polar 1-Manifold Toy Datasets.ipynb",
         "directed_circle": "01a02a Polar 1-Manifold Toy Datasets.ipynb",
         "directed_spiral": "01a02a Polar 1-Manifold Toy Datasets.ipynb",
         "directed_spiral_uniform": "01a02a Polar 1-Manifold Toy Datasets.ipynb",
         "directed_spiral_delayed": "01a02a Polar 1-Manifold Toy Datasets.ipynb",
         "generate_prism": "01a02b Polar 2-Manifold Toy Datasets.ipynb",
         "directed_cylinder": "01a02b Polar 2-Manifold Toy Datasets.ipynb",
         "directed_swiss_roll": "01a02b Polar 2-Manifold Toy Datasets.ipynb",
         "directed_swiss_roll_uniform": "01a02b Polar 2-Manifold Toy Datasets.ipynb",
         "directed_swiss_roll_sklearn": "01a02b Polar 2-Manifold Toy Datasets.ipynb",
         "add_labels": "01b02 Single-Cell Data and RNA Velocity.ipynb",
         "pancreas_rnavelo_load_data": "01b02 Single-Cell Data and RNA Velocity.ipynb",
         "pancreas_rnavelo": "01b02 Single-Cell Data and RNA Velocity.ipynb",
         "pancreas_rnavelo_pcs": "01b02 Single-Cell Data and RNA Velocity.ipynb",
         "d_rnavelo_load_data": "01b02 Single-Cell Data and RNA Velocity.ipynb",
         "d_rnavelo": "01b02 Single-Cell Data and RNA Velocity.ipynb",
         "d_rnavelo_pcs": "01b02 Single-Cell Data and RNA Velocity.ipynb",
         "plot_directed_2d": "01c Plotting Utils.ipynb",
         "plot_origin_3d": "01c Plotting Utils.ipynb",
         "plot_directed_3d": "01c Plotting Utils.ipynb",
         "plot_3d": "02b Diffusion Maps and Distances.ipynb",
         "display_flow_galary": "01c Plotting Utils.ipynb",
         "visualize_graph": "01c Plotting Utils.ipynb",
         "visualize_heatmap": "01c Plotting Utils.ipynb",
         "visualize_edge_index": "01c Plotting Utils.ipynb",
         "affinity_from_flow": "02a Flashlight Kernel.ipynb",
         "affinity_matrix_from_pointset_to_pointset": "02a Flashlight Kernel.ipynb",
         "make_sparse_safe": "02b Diffusion Maps and Distances.ipynb",
         "distance_matrix": "02b Diffusion Maps and Distances.ipynb",
         "anisotropic_kernel": "02b Diffusion Maps and Distances.ipynb",
         "adaptive_anisotropic_kernel": "02b Diffusion Maps and Distances.ipynb",
         "diffusion_matrix": "02b Diffusion Maps and Distances.ipynb",
         "diffusion_matrix_from_points": "02b Diffusion Maps and Distances.ipynb",
         "diffusion_coordinates": "02b Diffusion Maps and Distances.ipynb",
         "diffusion_map_from_points": "02b Diffusion Maps and Distances.ipynb",
         "diffusion_map_from_affinities": "02b Diffusion Maps and Distances.ipynb",
         "directed_neighbors": "02c Flow Neighborhoods.ipynb"}

modules = ["graph_datasets.py",
           "datasets.py",
           "data_processing.py"]

doc_url = "https://x.riddle.press/FlowNet/"

git_url = "https://github.com/professorwug/FlowNet/tree/master/"

def custom_doc_links(name): return None
