# Autogenerated by nbdev

d = { 'settings': { 'branch': 'master',
                'doc_baseurl': '/FRED/',
                'doc_host': 'https://x.riddle.press',
                'git_url': 'https://github.com/professorwug/FRED/tree/master/',
                'lib_path': 'FRED'},
  'syms': { 'FRED.core': {},
            'FRED.data_processing': {},
            'FRED.datasets': {},
            'FRED.eeemd': {},
            'FRED.embed': {},
            'FRED.graph_datasets': {},
            'FRED.inference': {},
            'FRED.metrics': {},
            'FRED.scheduling': {},
            'FRED.testing_utils': {},
            'FRED.trainers': {},
            'FRED.wild_fred': {}}}