# AUTOGENERATED! DO NOT EDIT! File to edit: nbs/04 Training Machinery/04a Scheduling.ipynb (unless otherwise specified).

__all__ = ['block_scheduler']

# Cell
class block_scheduler():
    def __init__(
            self,
            epoch_to_transition,
            loss_to_turn_on,
            weight = 1
    ):
        self.epoch_number = 0
        self.epoch_to_transition = epoch_to_transition
        self.loss_to_turn_on = loss_to_turn_on
        self.loss_weight = weight
    def __call__(self,loss_weights):
        self.epoch_number += 1
        if self.epoch_number > self.epoch_to_transition:
            loss_weights[self.loss_to_turn_on] = self.loss_weight
        else:
            if self.epoch_number > 1:
                loss_weights[self.loss_to_turn_on] = 0
        return loss_weights